### ISSUE TITLE
SVG 无法导出

### ISSUE THREAD

**Issue by Lotus-c** [leadream/figma-handoff#11]
每次导出都卡在svg元素上，无法导出

![批注 2020-04-20 155620](https://user-images.githubusercontent.com/4592854/79727778-806be180-831f-11ea-8a66-134152e12913.png)

**Comment by leadream** [comment]
@Lotus-c 麻烦给一个可以复现的脱敏文件链接，设置公开权限。

**Comment by Lotus-c** [comment]
> @Lotus-c 麻烦给一个可以复现的脱敏文件链接，设置公开权限。

今天好了

**Comment by Lotus-c** [comment]
又复现了https://www.figma.com/file/G4SW1XvlktFx2zpot8G2oo/%E6%B5%8B%E8%AF%95?node-id=0%3A1

**Comment by leadream** [comment]
@Lotus-c 
修复了，带遮罩的元素不能导出。
![image](https://user-images.githubusercontent.com/12868055/79820399-b613d780-83be-11ea-8f81-015a3a92f614.png)
