### ISSUE TITLE
svg导不出来

### ISSUE THREAD

**Issue by Lotus-c** [leadream/figma-handoff#12]
又遇到一个svg导不出的情况（https://www.figma.com/file/G4SW1XvlktFx2zpot8G2oo/%E6%B5%8B%E8%AF%95?node-id=0%3A1）
![image](https://user-images.githubusercontent.com/4592854/79830918-ff712080-83d8-11ea-82d6-f8b720b5da10.png)

**Comment by leadream** [comment]
@Lotus-c 
![image](https://user-images.githubusercontent.com/12868055/79836572-e40b1300-83e2-11ea-826a-db2dc031a927.png)

这个图标里面是全透明的，你自己先检查一下文件。

**Comment by Lotus-c** [comment]
![image](https://user-images.githubusercontent.com/4592854/79840624-baed8100-83e8-11ea-9642-03d48a886bc6.png)

有问题好像是这个

**Comment by leadream** [comment]
@Lotus-c 
是这个 compass
![image](https://user-images.githubusercontent.com/12868055/79856930-9650d380-83ff-11ea-92b8-6170ac9728e4.png)

**Comment by leadream** [comment]
@Lotus-c 看下面的错误提示。
