### ISSUE TITLE
切图命名问题 - 希望不要改变导出切图文件的命名或者使用下划线 _

### ISSUE THREAD

**Issue by herobinge** [leadream/figma-handoff#14]
您好：
         希望不要改变导出切图文件的命名或者使用下划线 _
ps: Handoff 是一款相当优秀的插件，十分感谢。

**Comment by leadream** [comment]
@herobinge 斜线吗？命名不能包含斜线，不然会直接变成一层层的文件夹。以后会支持切图中的斜线替换功能。

**Comment by herobinge** [comment]
> @herobinge 斜线吗？命名不能包含斜线，不然会直接变成一层层的文件夹。以后会支持切图中的斜线替换功能。

不是斜线，是下划线;  通常APP倾向于ic_home.png  前段开发倾向于 ic-home.png。 （所以希望在导出时不要更改切图命名）

**Comment by leadream** [comment]
@herobinge 你是说下划线被替换了吗？还是说希望用下划线拼接切图命名？

**Comment by herobinge** [comment]
> @herobinge 你是说下划线被替换了吗？还是说希望用下划线拼接切图命名？

![image 1](https://user-images.githubusercontent.com/13134497/79870799-17b36080-8416-11ea-9eaf-43f4b0315eba.png)
请看我用红线标记的地方呢？

**Comment by leadream** [comment]
@herobinge 明白了，近期改一下。

**Comment by leadream** [comment]
@herobinge 切图命名风格现在可以自己选了。
