### ISSUE TITLE
导出的交付文件有些图层会被合并掉

### ISSUE THREAD

**Issue by palmer-chen** [leadream/figma-handoff#15]

**Comment by palmer-chen** [comment]
导出到本地时，有些组件直接变成一个图层，失去了本来到图层结构

**Comment by leadream** [comment]
@palmer-chen  是不是布尔运算的？布尔运算的元素不可以选择里面的东西。如果不是的话，麻烦发一个脱敏文件链接。

**Comment by palmer-chen** [comment]
我重新研究了一下，是我文件的问题，因为sketch描边和填充颜色不能使用同一个样式，所以我在组件最上层做了一个跟组件一样尺寸的描边图层，导入figma之后就一起带过去了，而Juuust Handoff导出的文件，鼠标无法穿透这个只有描边的图层来选择其底下的对象，所以看起来好像组件被合并了

**Comment by leadream** [comment]
@palmer-chen 好的，那我关了哦。
