### ISSUE TITLE
frame排序问题

### ISSUE THREAD

**Issue by CarsonLam** [leadream/figma-handoff#16]
为什么frame是倒序排列的？

**Comment by leadream** [comment]
因为在 Figma 中后创建的 frame 会在上面，但是设计时一般会把后创建的往下面排，所以为了符合视觉上的顺序，frame 列表做了倒序处理。
![image](https://user-images.githubusercontent.com/12868055/80373761-22fc0580-88c8-11ea-90a5-9814ec8a73ef.png)
