### ISSUE TITLE
侧边栏的宽度能否加一个鼠标拖拽改变其宽度的功能

### ISSUE THREAD

**Issue by palmer-chen** [leadream/figma-handoff#18]
项目页面多的时候页面命名也会变得复杂，侧边栏宽度不够无法很好的通过页面名称来理解页面结构

**Comment by leadream** [comment]
鼠标放一会会显示完整标题的，我准备再加一个搜索，你看能解决你的问题吗？

**Comment by palmer-chen** [comment]
> 鼠标放一会会显示完整标题的，我准备再加一个搜索，你看能解决你的问题吗？

单个页面的完整标题从导航栏那里也是可以看得到，我希望的是侧边栏不仅仅是作为目录的功能，它应该是能让查看的人通过这个目录看到整个项目的结构。
另外搜索功能也不错，我觉得还可以加一个排序

**Comment by leadream** [comment]
@palmer-chen 因为 Figma 里面 page 是单层级的，所以侧边栏目前就只有一层。你所说的项目结构是怎么区分的呢？是用一些空白页面来间隔吗（如下图）？
![image](https://user-images.githubusercontent.com/12868055/80584301-0ab0f580-8a44-11ea-865c-bd1afd7ba3c7.png)

**Comment by leadream** [comment]
@palmer-chen 
目前添加了一个可以搜索的选择器，也能看到 page->frame 的结构，不知道是否解决了你的问题？
![image](https://user-images.githubusercontent.com/12868055/80831946-54edce80-8c1e-11ea-8504-47100aac0ab7.png)

**Comment by palmer-chen** [comment]
不是加空页面，是通过页面命名来理解页面结构，但是侧边栏宽度固定的话，当我命名太长了，后面就会变成省略号，这样就不太好理解这个页面是什么
<img width="240" alt="202005081129" src="https://user-images.githubusercontent.com/62734948/81367436-d2827480-911f-11ea-90a0-85c18791aae3.png">

**Comment by leadream** [comment]
@palmer-chen 鼠标浮在上面显示完整名称，然后建议你根据「文件->page->frame」的形式分好类，不要全部放在一个文件，结合现在优化的可以搜索的页面选择器来使用。

不会做页面名称解析和可边宽度，先关闭了。
