### ISSUE TITLE
第一次用，卡在processing上不动了，按钮进度条没反应，求帮助

### ISSUE THREAD

**Issue by fanrry318** [leadream/figma-handoff#20]
macOS 10.14.5，chrome 81.0.4044.129（正式版本）

**Comment by leadream** [comment]
@fanrry318 插件吗？还是 web？

**Comment by fanrry318** [comment]
@leadream 是插件

**Comment by leadream** [comment]
@fanrry318 麻烦给一个可复现的脱敏文件链接。

**Comment by MispRonger** [comment]
@leadream 如果的Frame选中很多，Processing File就会非常缓慢，不知道是卡住了、还是在继续进行中
有时候导出到一半也会卡住

**Comment by fanrry318** [comment]
> @leadream 如果的Frame选中很多，Processing File就会非常缓慢，不知道是卡住了、还是在继续进行中
> 有时候导出到一半也会卡住

不知如何给您脱敏文件，我没有选很多Frame里就两个方框，卡了半小时没动静

**Comment by leadream** [comment]
@MispRonger 
如果显示 Processing File 那就是在处理文件，文件内容太多，切图太多都需要时间。

**Comment by leadream** [comment]
@fanrry318 脱敏文件，就是复制一份文件出来，脱除敏感信息，确定该文件导出时间很长，把这个文件设置为任何人可以查看，把链接贴到这里。

**Comment by leadream** [comment]
@fanrry318 没有文件我没法排查。

**Comment by fanrry318** [comment]
https://www.figma.com/file/vzIBPobxfmriXJ67tHqAzf/Untitled?node-id=1%3A2

**Comment by leadream** [comment]
@fanrry318 404，设置一下任何人可见。

**Comment by fanrry318** [comment]
设置好了

**Comment by isakula** [comment]
我这边也是遇到这种情况，用的是figma插件，chrome浏览器没有一次成功过，一直是processing html，换成safari浏览器是可以的。

**Comment by MispRonger** [comment]
@leadream 
**macOS** Catalina 10.15.4 (19E287) 
Figma客户端使用插件，导出一份105页，未勾选高清和组建，2h一直是Processing File
😹

**Comment by leadream** [comment]
@MispRonger 文件太大了，这个我没办法，你自己把文件分一分吧。

**Comment by leadream** [comment]
@fanrry318 @isakula 知道问题出在哪了，近期会修复的。

**Comment by fanrry318** [comment]
哇，谢谢大佬

**Comment by leadream** [comment]
@fanrry318 已经改了，试一下。

**Comment by fanrry318** [comment]
好了！太感谢了！大佬厉害！

**Comment by leadream** [comment]
Ok，那我关了这个一休。
