### ISSUE TITLE
切图名称重复问题

### ISSUE THREAD

**Issue by maomao-rgb** [leadream/figma-handoff#21]
首先感谢作者的辛勤付出，我这里有一个疑问，就是切片导出命名有些问题，如图：
![image](https://user-images.githubusercontent.com/65207007/81632691-809e5f00-943d-11ea-824d-7668d09a273c.png)
如果是二倍图之类的命名，后缀会重复一个“-@2x-n”，不知道是不是我操作有问题，已经尝试很多遍了，希望得到作者的解答，谢谢～

**Comment by leadream** [comment]
现在为了避免重复重名，每个后面都加了一个唯一的数字，后面我会解决这个问题的。

**Comment by maomao-rgb** [comment]
> 现在为了避免重复重名，每个后面都加了一个唯一的数字，后面我会解决这个问题的。

谢谢解答

**Comment by leadream** [comment]
@maomao-rgb 已经解决，可以试一下。

**Comment by maomao-rgb** [comment]
我已经用了，谢谢大佬
------------------------------------------------------------------
发件人：Jun <notifications@github.com>
发送时间：2020年6月15日(星期一) 18:16
收件人：leadream/figma-handoff <figma-handoff@noreply.github.com>
抄　送：maomao-rgb <maoerxian@aliyun.com>; Mention <mention@noreply.github.com>
主　题：Re: [leadream/figma-handoff] 切图名称重复问题 (#21)

@maomao-rgb 已经解决，可以试一下。
