### ISSUE TITLE
标注和内容有偏移现象

### ISSUE THREAD

**Issue by palmer-chen** [leadream/figma-handoff#22]
按我的理解应该是图片整体尺寸比实际小了（或者说标注整体比图片大了），导致从左上角开始每一个元素的标注跟内容的错位越来越大
<img width="722" alt="屏幕快照 2020-05-18 下午6 25 53" src="https://user-images.githubusercontent.com/62734948/82203985-b1e3c700-9936-11ea-9de6-f295cbc449b0.png">
<img width="1083" alt="屏幕快照 2020-05-18 下午6 30 15" src="https://user-images.githubusercontent.com/62734948/82203991-b4deb780-9936-11ea-8a92-6fb87ee17bce.png">

**Comment by leadream** [comment]
@palmer-chen 内部有元素（或投影）超出了最外层 Frame，并且最外层 Frame 没有勾选 clip content。
https://figmacn.com/handoff-landing#other-attentions
https://juuun.io/tutorial/juuust-handoff-usage-tutorial/
