### ISSUE TITLE
为什么老是删掉我提的问题？？？

### ISSUE THREAD

**Issue by palmer-chen** [leadream/figma-handoff#23]
首先很感谢你做的这个项目，但是我提出的bug问题我想都不是无端取闹吧，既然存在问题，那就应该共同去解决，为何你不解决反而删掉我的问题，这已经不是第一次了，你从一开始到现在已经删了我提出的三个问题点，我也没有做什么冒犯你的事，你这又是为哪般？

**Comment by leadream** [comment]
@palmer-chen 我给你解决方案了啊，错位一般就是内部元素溢出导致的，没有怪你的意思啊，Github 上面开发者知道问题在哪的话，给出解决方案，或者觉得这个不是 bug，或者没有计划修复，一般就会关闭 issue，没有任何冒犯你的意思。
