### ISSUE TITLE
导航菜单使用疑问

### ISSUE THREAD

**Issue by CarsonLam** [leadream/figma-handoff#24]
![image](https://user-images.githubusercontent.com/26378212/82288610-75b37380-99d5-11ea-837c-6ccfb697efd0.png)
您好，左侧导航菜单，能改为鼠标hover在一级菜单上时：显示右侧二级菜单。点击一级菜单进入页面吗？

**Comment by leadream** [comment]
@CarsonLam 我看一下。

**Comment by leadream** [comment]
@CarsonLam 欧了。
