### ISSUE TITLE
切图问题

### ISSUE THREAD

**Issue by Nobit93** [leadream/figma-handoff#27]
1、导出时需要保持在 Figma 中原有的切图命名，不需要后面加序号，开发可以直接使用。如果有重名的切图最好能给个提示或者直接保留一个就行。
![image](https://user-images.githubusercontent.com/22189438/84225446-b7859480-ab11-11ea-9192-3c89dcc53a84.png)

2、有没有办法做到在 master component 中建立了切图导出，所有复用到的地方都能直接点击下载切图？

多谢。

**Comment by leadream** [comment]
@Nobit93 谢谢反馈，第一个问题正在优化，第二个我会考虑的。

**Comment by leadream** [comment]
@Nobit93 现在可以选择切图了，重命名问题也解决了。
