### ISSUE TITLE
关于导航优化建议

### ISSUE THREAD

**Issue by CarsonLam** [leadream/figma-handoff#31]
【问题】
![image](https://user-images.githubusercontent.com/26378212/86223648-63bf1600-bbba-11ea-951c-2d792ff11a80.png)

【期望】
1. 导航弹框视图有点小，能否加长点。（做的项目page都比较多，十几二十页）
2. 能否支持点击一级导航就能打开页面，（每次都要点击二级导航，有点麻烦）

**Comment by leadream** [comment]
@CarsonLam 收到，后续会优化的。

**Comment by leadream** [comment]
已支持。
