### ISSUE TITLE
期待后续可以实现隐藏侧栏，全屏百分百查看哈哈

### ISSUE THREAD

**Issue by huangzhongzhong** [leadream/figma-handoff#38]

**Comment by IvanID** [comment]
同求，桌面端界面100%目前不太容易查看。

**Comment by leadream** [comment]
@huangzhongzhong @IvanID 已经支持。
![image](https://user-images.githubusercontent.com/12868055/103599128-5571fe00-4f3f-11eb-94da-ccd76950ece2.png)
