### ISSUE TITLE
最近为什么导出后页面是空白的？

### ISSUE THREAD

**Issue by blacksco666** [leadream/figma-handoff#42]
2.d16cc855.chunk.js:1 TypeError: Cannot read property 'icon' of undefined
    at main.4b1c5d6f.chunk.js:1
    at da (2.d16cc855.chunk.js:1)
    at As (2.d16cc855.chunk.js:1)
    at Mu (2.d16cc855.chunk.js:1)
    at Pu (2.d16cc855.chunk.js:1)
    at ku (2.d16cc855.chunk.js:1)
    at mu (2.d16cc855.chunk.js:1)
    at il (2.d16cc855.chunk.js:1)
    at 2.d16cc855.chunk.js:1
    at xu (2.d16cc855.chunk.js:1)
ms @ 2.d16cc855.chunk.js:1
2.d16cc855.chunk.js:1 Uncaught TypeError: Cannot read property 'icon' of undefined
    at main.4b1c5d6f.chunk.js:1
    at da (2.d16cc855.chunk.js:1)
    at As (2.d16cc855.chunk.js:1)
    at Mu (2.d16cc855.chunk.js:1)
    at Pu (2.d16cc855.chunk.js:1)
    at ku (2.d16cc855.chunk.js:1)
    at mu (2.d16cc855.chunk.js:1)
    at il (2.d16cc855.chunk.js:1)
    at 2.d16cc855.chunk.js:1
    at xu (2.d16cc855.chunk.js:1)
index.html:1 Access to internal resource at 'file:///C:/Users/Administrator/Desktop/%E5%BC%80%E5%9F%BA%E9%A1%B9%E7%9B%AE%E6%89%8B%E6%9C%BA%E7%89%880730/manifest.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Administrator/Desktop/%E5%BC%80%E5%9F%BA%E9%A1%B9%E7%9B%AE%E6%89%8B%E6%9C%BA%E7%89%880730/static/js/2.d16cc855.chunk.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Administrator/Desktop/%E5%BC%80%E5%9F%BA%E9%A1%B9%E7%9B%AE%E6%89%8B%E6%9C%BA%E7%89%880730/static/js/main.4b1c5d6f.chunk.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Administrator/Desktop/%E5%BC%80%E5%9F%BA%E9%A1%B9%E7%9B%AE%E6%89%8B%E6%9C%BA%E7%89%880730/static/css/2.3bd2137c.chunk.css.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/Administrator/Desktop/%E5%BC%80%E5%9F%BA%E9%A1%B9%E7%9B%AE%E6%89%8B%E6%9C%BA%E7%89%880730/static/css/main.732a37e8.chunk.css.map: System error: net::ERR_FILE_NOT_FOUND

**Comment by leadream** [comment]
@blacksco666 加我微信（bujidewodeweixinhao），发链接给我。

**Comment by leadream** [comment]
已修复。
https://github.com/leadream/figma-handoff/commit/ff3b52a2924ce45c20ba647bc54036192d9351bd
