### ISSUE TITLE
阴影的代码不正确，开发复制后实现效果不一致

### ISSUE THREAD

**Issue by abcok668** [leadream/figma-handoff#43]
复制FIGMA原生的阴影代码是正常显示效果，但是handoff的阴影代码就会显示不正确，这个是否可以修复一下谢谢。

**Comment by leadream** [comment]
@abcok668 可以给一下更多信息吗？可复现 Figma 文件链接，两边复制的代码这些。

**Comment by leadream** [comment]
无详细信息，暂时关闭。
