### ISSUE TITLE
无法下载全部切图

### ISSUE THREAD

**Issue by BISCAY-W** [leadream/figma-handoff#44]
在右侧切图的顶部没有出现“下载全部切图”的按钮

**Comment by leadream** [comment]
@BISCAY-W 本地文件没有这个选项，直接在文件夹里面找切图就行了，只有把它托管到服务器才有这个。

**Comment by leadream** [comment]
@BISCAY-W 本地文件没有这个选项，直接在文件夹里面找切图就行了，只有把它托管到服务器才有这个。
