### ISSUE TITLE
[关于切图]figma 里标记的图层组没有明确标识

### ISSUE THREAD

**Issue by luJun0213** [leadream/figma-handoff#5]
figma 里标记的图层在 handoff 里没有明确的范围标识，而且切图内的元素全部可以点击，使得开发很难找到切图的实际大小及坐标。  可不可以像蓝湖一样切图有标识切图层元素不可选

**Comment by leadream** [comment]
@luJun0213 Figma 的切图不是单独的 Slice，也是普通元素，不过上面有切图标记。我可以把切图像组件那样标记出来，你看这样可以解决你的问题吗？

**Comment by luJun0213** [comment]
可以，这样开发看到应该会更明确一些。  另外昨天我又自己试了一下  使用 slice 是没有问题的，问题出在我是直接标记 export

**Comment by leadream** [comment]
我没有支持 Slice 哦，Slice 看起来是一个过渡方案，不推荐使用 Slice 进行切图，还是推荐使用 Export。

**Comment by leadream** [comment]
@luJun0213 选中最外层可以看到当前所有切图（在页面上有红色标注，右侧有列表）：
<img width="800" alt="WX20200311-145740@2x" src="https://user-images.githubusercontent.com/12868055/76390713-dd7f8980-63a8-11ea-869d-76d29982b321.png">
