### ISSUE TITLE
单个页面导出卡住，试了很多次还是一样。（有的页面可导出并很快）

### ISSUE THREAD

**Issue by cream598** [leadream/figma-handoff#50]
![image](https://user-images.githubusercontent.com/57975542/105659383-98ead700-5f03-11eb-837a-34587c08fc3a.png)

**Comment by leadream** [comment]
@cream598 把这个文件放到 Drafts 中，使用邮箱 leadream4@gmail.com 邀请我编辑，我帮你排查一下（Drafts 中的文件邀请编辑不需要付费）。

**Comment by cream598** [comment]
好的 已经分享给你了（可编辑），链接不方便发出来，但是名称可以告诉你：首页结构信息分发，目前不能导出的是第一张、第二张画布，后面的我通过减少图层和重命名解决了。但是前两张怎么改还是导不出来

**Comment by leadream** [comment]
@cream598 不用公开链接，我收到了，待我研究一下。

**Comment by leadream** [comment]
@cream598 你的设计是从 Sketch 导入的吗？里面有很多空的布尔元素，导致文件解析出错，全部删掉就好了。我给插件加一个功能，来查找这些幽灵布尔元素，不过你自己设计时也要注意随手删掉无用元素。

![image](https://user-images.githubusercontent.com/12868055/106459193-77be5380-64cc-11eb-8aa1-97a513793072.png)

**Comment by cream598** [comment]
谢谢～ 是的 有些部分是从sketch导入的。
