### ISSUE TITLE
新版本导出的文件查看时一片空白

### ISSUE THREAD

**Issue by Muxingzi5520** [leadream/figma-handoff#51]
我今天要交付的文件，在导出文件后，交给开发，开发那边无论使用哪个浏览器，打开文件后都是一片空白的界面，报错669个。我在自己电脑上也只有使用chrome可以打开，其他浏览器打开也是一片空白。

**Comment by leadream** [comment]
可以发压缩包给我吗？leadream4@gmail.com

**Comment by leadream** [comment]
@Muxingzi5520 已修复。
