### ISSUE TITLE
升级98.13版后使用出现错误提示

### ISSUE THREAD

**Issue by ryyyry** [leadream/figma-handoff#56]
浏览器和离线客户端都报错，如图
<img width="318" alt="Screen Shot 2021-06-03 at 11 55 27 AM" src="https://user-images.githubusercontent.com/84903416/120584451-99235200-c462-11eb-96bc-5ba26c8bfe60.png">

后面经过测试，发现画板内有切图时会导致报错，麻烦大大看下是什么情况……

**Comment by Shilem** [comment]
遇到相同问题，更新客户端后导出时包含切图即提示错误“解析时出了点问题”，去掉勾选可正常导出

**Comment by leadream** [comment]
Figma 改了点东西导致的，我晚上回去修复，暂时只能先去掉所有 export。

**Comment by leadream** [comment]
已修复。
