### ISSUE TITLE
导出的标注无法选中查看

### ISSUE THREAD

**Issue by yuyuyu926** [leadream/figma-handoff#58]
https://www.figma.com/file/B5n6wfiz7QXb2SuBVAGOPc/%E8%A7%84%E5%88%99?node-id=0%3A1

![image](https://user-images.githubusercontent.com/86344734/123054462-78359780-d437-11eb-8d91-904d4d294f7d.png)
文本框的位置也有偏差，
已开启编辑权限，您可以自己导出看看

**Comment by leadream** [comment]
@yuyuyu926 打不开文件，麻烦直接邀请我邮箱 leadream4@gmail.com。

**Comment by leadream** [comment]
元素翻转导致的错位，已知问题，暂时先关闭。
