### ISSUE TITLE
导出的离线包打开左侧栏按数字/首字母排序

### ISSUE THREAD

**Issue by miraeqqqqq** [leadream/figma-handoff#59]
导出工具很好用，但是左侧栏排序没有规律，开发看着看着就找不到图了，希望优化一下，万分感谢

**Comment by leadream** [comment]
@miraeqqqqq 你好，你可以决定左侧顺序的，请查看文档：
https://docs.heron.design/designer/#heron-%E5%B7%A6%E4%BE%A7%E9%A1%B5%E9%9D%A2%E7%9A%84%E9%A1%BA%E5%BA%8F%E6%98%AF%E7%94%B1%E8%B0%81%E5%86%B3%E5%AE%9A%E7%9A%84

按首字母排序这些后续会加上。

**Comment by leadream** [comment]
@miraeqqqqq 现在你可以在插件上设定排序方式了。
![image](https://user-images.githubusercontent.com/12868055/129452715-10a34ed6-470b-488c-b7c8-050f13866f23.png)
