### ISSUE TITLE
[feature] 希望新增导出原型链接功能

### ISSUE THREAD

**Issue by yanghuayi** [leadream/figma-handoff#9]
有原型链接功能后，研发才清楚页面逻辑结构

**Comment by yanghuayi** [comment]
[add] 希望新增页面搜索功能，一般项目都有10-50个页面，没有搜索功能有点困难

**Comment by leadream** [comment]
@yanghuayi 页面搜索可以，原型建议直接使用 Figma 的链接，因为他们接口没开放原型的数据，我做不了。

**Comment by yanghuayi** [comment]
@leadream 原型链接这个问题，现在figma的问题比较严重，预览加载第一次要好几分钟，完全无法接受，我现在想的方案是，我们自己做原型链接功能，数据先用浏览器的localStorage去缓存，下载保存的时候，生成一个json文件，我空了，我来研究这个功能，给你提PR, 搜索这个功能比较简单，你就直接弄了

**Comment by leadream** [comment]
@yanghuayi 你的网络那么慢吗？我感觉开一个梯子把 figma.com 加入 PAC 列表就能解决了，没必要大动干戈。

**Comment by yanghuayi** [comment]
但是给研发或者客户演示的时候，你不可能叫客户搭梯子去看吧

**Comment by leadream** [comment]
@yanghuayi 那你尝试一下吧，感觉还挺麻烦的。
